project:
  type: website

website:
  title: "Ian Jordy Lopez Diaz"
  description: "Data Scientist / Data Analyst"
  site-url: "https://ianlopezdiaz.github.io/portfolio"
  navbar: false
  page-footer:
    left: "© 2025 ianlopezdiaz"
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      dark: solar
      light: minty
    theme-toggle: true
    css: styles.css

